version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:inception
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: on-failure
  
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
    - inception
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
 
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
    - inception
    depends_on:
    - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    volumes:
    - wordpress:/var/www/wordpress
    expose:
    - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME_PATH}/data-mariadb
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME_PATH}/data-wordpress

networks:
  inception:
    driver: bridge
