services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
    - inception
    build:
      context: ./requirements/mariadb/
        #volumes:
        # - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    env_file: .env
 
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: on-failure
 
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
    - inception
    depends_on:
    - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    volumes:
    - wordpress:/var/www/wordpress
    expose:
    - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/inception/data-mariadb
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/inception/data-wordpress

networks:
  inception:
    driver: bridge
