version: '3.7'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    networks:
    - inception
    build:
      context: ./requirements/mariadb/
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
 
  nginx:
    container_name: nginx
    image: nginx
    init: true
    networks:
      - inception
    depends_on:
      - mariadb
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: unless-stopped
 
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
    - inception
    depends_on:
    - mariadb
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
    - wordpress:/var/www/wordpress
    expose:
    - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/inception/data-mariadb
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/inception/data-wordpress
networks:
  inception:
    driver: bridge
